package com.example.bankamat.Enum;

public enum Huquqlar {
    KIRIMCHIQIMROYHATI,PULMIQDORI,MYKIRIMCHIQIMROYHATI,MYPULMIQDORI,
    ADDXODIM,DELETEXODIM,EDITXODIM,READXODIM,
    READMYXODIM,EDITMYXODIM
}
